channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib=3.1.3
  - numpy=1.18.1
  - scipy=1.4.1
  - pandas=1.0.1
  - xarray=0.15.0
  - dask=2.11.0
  - netcdf4=1.5.3
  - wrf-python=1.3.2
  - utm=0.5.0
  - f90nml=1.1.2
  - elevation=1.0.6
  - rasterio=1.0.25
